---
knit: bookdown::render_book
documentclass: book
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    template: templates/template.tex
    keep_tex: true
    citation_package: natbib
    pandoc_args: ["--lua-filter=scripts_and_filters/correction_filter.lua"] #comment out to stop applying blue background to inline corrections
  bookdown::gitbook:
    link-citations: true
    css: style.css
    keep_md: true
  bookdown::word_document2: default   #NOTE: EXPERIMENTAL
params:
  corrections: false # set false to stop applying blue background to blocks of corrections
title: |
  Improving the Development and Validation \
  of Early Warning Scores
author: Stephen Gerry
bibliography:
#  - packages.bib
  - EWSpapers.bib
github-repo: 
twitter-handle: 
college: Green Templeton College
degree: Doctor of Philosophy
degreedate: Michaelmas 2020
abstract: |
  `r paste(readLines("text/_abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r paste(readLines("text/_acknowledgements.Rmd"), collapse = '\n  ')`
abbreviations: text/abbreviations #without file extension
bib-humanities: false   #set to true if you want in-text references formatted as author-year
abstractseparate: true  #include front page w/ abstract for examination schools?
toc-depth: 2
lof: true #list of figures in front?
lot: true #list of tables in front?
mini-toc: true  #mini-table of contents at start of each chapter? (this just prepares it; you must also add \minitoc after the chapter titles)
mini-lot: false  #mini-list of tables by start of each chapter?
mini-lof: false  #mini-list of figures by start of each chapter?
draft: false
page-layout: nobind #'nobind' for PDF output (equal margins), 'twoside' for two-sided binding (mirror margins and blank pages), leave blank for one-sided binding (left margin > right margin)
---

<!-- NOTE ON COMPILING YOUR THESIS: 
- if you want to compile the whole thesis, click 'Build Book' over on the Build tab; if you just click 'knit' on Index.Rmd, it may just put "Placeholder" as text in individual chapters instead of compiling all the conten¨¨
- compiling your thesis will leave a lot of files in your working directory, mostly for the mini tables of content - you can run the command 'file.remove(list.files(pattern = ".log$|.maf$|.mtc"))' in the R console to remove them in one go
 -->


```{r create_chunk_options, include=FALSE}
source('scripts_and_filters/create_chunk_options.R')
```
<!-- NOTE ON CREATING NEW CHUNK OPTIONS: 
- include the create_chunk_options chunk above at the top of your index.Rmd file
- this adds code to create additional chunk options you need (e.g. for adding author references to the quotes you see at the top of chapter 1 and 4 with r markdown rather than latex syntax)
- if you need to create additional chunk options for your own purposes, I recommend you do it in the file scripts/create_chunk_options.R to avoid clutter in index.Rmd
-->

```{r package_check, include=FALSE}
# List of packages required
pkg <- c("devtools", "bookdown")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")

if (!("thesisdown" %in% installed.packages()))
  devtools::install_github("ismayc/thesisdown")
```










